INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('John', 'Doe');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Jane', 'Doe');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Pippin', 'Laney');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Garry', 'Geoff');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Spencer', 'Rue');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Lizzie', 'Elly');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Jemima', 'Julia');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Lorie', 'Minerva');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Angelina', 'Jed');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Evie', 'Ivan');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Catharine', 'Foster');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Flora', 'Wilmer');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Beth', 'Krystal');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Brendon', 'Isaiah');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Harris', 'America');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Johnathan', 'Love');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Yancy', 'Elliott');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Kim', 'Norah');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Vera', 'Layne');
INSERT INTO `customers` (`first_name`, `last_name`) VALUES ('Jayme', 'Horace');

INSERT INTO `products` (title, price) VALUES ('Halo Infinite', 54.99);
INSERT INTO `products` (title, price) VALUES ('Halo 5', 21.99);
INSERT INTO `products` (title, price) VALUES ('Halo 4', 12.99);
INSERT INTO `products` (title, price) VALUES ('Halo 3', 4.99);
INSERT INTO `products` (title, price) VALUES ('Halo 2', 7.99);
INSERT INTO `products` (title, price) VALUES ('Halo: Combat Evolved', 9.99);
INSERT INTO `products` (title, price) VALUES ('Battlefield 2042', 54.99);
INSERT INTO `products` (title, price) VALUES ('Mass Effect', 17.99);
INSERT INTO `products` (title, price) VALUES ('Mass Effect 2', 24.99);
INSERT INTO `products` (title, price) VALUES ('Mass Effect 3', 17.99);
INSERT INTO `products` (title, price) VALUES ('Mass Effect: Andromeda', 24.99);
INSERT INTO `products` (title, price) VALUES ('Grand Theft Auto V', 19.99);
INSERT INTO `products` (title, price) VALUES ('Star Wars Battlefront', 14.49);
INSERT INTO `products` (title, price) VALUES ('Star Wars Battlefront II', 34.49);
INSERT INTO `products` (title, price) VALUES ('Star Wars Jedi: Fallen Order', 34.99);
INSERT INTO `products` (title, price) VALUES ('Star Wars: Squadrons', 34.99);
INSERT INTO `products` (title, price) VALUES ('Star Wars: Battlefront 2 (Classic)', 7.19);
INSERT INTO `products` (title, price) VALUES ('Star Wars - Knights of the Old Republic', 7.19);
INSERT INTO `products` (title, price) VALUES ('Halo: The Master Chief Collection', 29.99);
INSERT INTO `products` (title, price) VALUES ('PUBG: BATTLEGROUNDS', 26.99);
INSERT INTO `products` (title, price) VALUES ('Call Of Duty: Black Ops III', 44.99);
INSERT INTO `products` (title, price) VALUES ('Arma 3', 5.99);
INSERT INTO `products` (title, price) VALUES ('PAYDAY', 8.99);
INSERT INTO `products` (title, price) VALUES ('Tom Clancy's Rainbow Six Seige', 16.99);
INSERT INTO `products` (title, price) VALUES ('Borderlands 3', 49.99);

INSERT INTO `orders` (fk_customer_id) VALUES (2);
INSERT INTO `orders` (fk_customer_id) VALUES (3);
INSERT INTO `orders` (fk_customer_id) VALUES (4);
INSERT INTO `orders` (fk_customer_id) VALUES (5);
INSERT INTO `orders` (fk_customer_id) VALUES (6);
INSERT INTO `orders` (fk_customer_id) VALUES (7);
INSERT INTO `orders` (fk_customer_id) VALUES (8);
INSERT INTO `orders` (fk_customer_id) VALUES (9);
INSERT INTO `orders` (fk_customer_id) VALUES (10);
INSERT INTO `orders` (fk_customer_id) VALUES (11);
INSERT INTO `orders` (fk_customer_id) VALUES (12);
INSERT INTO `orders` (fk_customer_id) VALUES (13);

INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (2, 3, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (2, 14, 3); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (3, 3, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (4, 23, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (5, 11, 2); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (5, 19, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (6, 1, 2); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (7, 12, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (8, 4, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (9, 2, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (10, 17, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (11, 13, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (12, 26, 1); 
INSERT INTO `order_items` (fk_order_id, fk_product_id, order_quantity) VALUES (13, 21, 1); 
